-- Radarly Stock Seed Data (414 stocks)
-- Paste this in phpMyAdmin SQL tab after running migration.sql

INSERT INTO stocks_master (symbol, company_name, exchange, sector, is_active) VALUES
('RELIANCE', 'Reliance Industries Ltd', 'NSE', 'Oil Gas & Consumable Fuels', 1),
('TCS', 'Tata Consultancy Services Ltd', 'NSE', 'Information Technology', 1),
('HDFCBANK', 'HDFC Bank Ltd', 'NSE', 'Financial Services', 1),
('INFY', 'Infosys Ltd', 'NSE', 'Information Technology', 1),
('ICICIBANK', 'ICICI Bank Ltd', 'NSE', 'Financial Services', 1),
('HINDUNILVR', 'Hindustan Unilever Ltd', 'NSE', 'FMCG', 1),
('SBIN', 'State Bank of India', 'NSE', 'Financial Services', 1),
('BHARTIARTL', 'Bharti Airtel Ltd', 'NSE', 'Telecommunication', 1),
('ITC', 'ITC Ltd', 'NSE', 'FMCG', 1),
('KOTAKBANK', 'Kotak Mahindra Bank Ltd', 'NSE', 'Financial Services', 1),
('LT', 'Larsen & Toubro Ltd', 'NSE', 'Construction', 1),
('AXISBANK', 'Axis Bank Ltd', 'NSE', 'Financial Services', 1),
('BAJFINANCE', 'Bajaj Finance Ltd', 'NSE', 'Financial Services', 1),
('ASIANPAINT', 'Asian Paints Ltd', 'NSE', 'Consumer Durables', 1),
('MARUTI', 'Maruti Suzuki India Ltd', 'NSE', 'Automobile', 1),
('TITAN', 'Titan Company Ltd', 'NSE', 'Consumer Durables', 1),
('SUNPHARMA', 'Sun Pharmaceutical Industries', 'NSE', 'Healthcare', 1),
('HCLTECH', 'HCL Technologies Ltd', 'NSE', 'Information Technology', 1),
('WIPRO', 'Wipro Ltd', 'NSE', 'Information Technology', 1),
('TATAMOTORS', 'Tata Motors Ltd', 'NSE', 'Automobile', 1),
('ULTRACEMCO', 'UltraTech Cement Ltd', 'NSE', 'Construction Materials', 1),
('NTPC', 'NTPC Ltd', 'NSE', 'Power', 1),
('NESTLEIND', 'Nestle India Ltd', 'NSE', 'FMCG', 1),
('POWERGRID', 'Power Grid Corp of India', 'NSE', 'Power', 1),
('M&M', 'Mahindra & Mahindra Ltd', 'NSE', 'Automobile', 1),
('TATASTEEL', 'Tata Steel Ltd', 'NSE', 'Metals & Mining', 1),
('TECHM', 'Tech Mahindra Ltd', 'NSE', 'Information Technology', 1),
('ONGC', 'Oil & Natural Gas Corp', 'NSE', 'Oil Gas & Consumable Fuels', 1),
('JSWSTEEL', 'JSW Steel Ltd', 'NSE', 'Metals & Mining', 1),
('COALINDIA', 'Coal India Ltd', 'NSE', 'Metals & Mining', 1),
('ADANIENT', 'Adani Enterprises Ltd', 'NSE', 'Metals & Mining', 1),
('BAJAJFINSV', 'Bajaj Finserv Ltd', 'NSE', 'Financial Services', 1),
('GRASIM', 'Grasim Industries Ltd', 'NSE', 'Construction Materials', 1),
('DRREDDY', 'Dr. Reddys Laboratories', 'NSE', 'Healthcare', 1),
('CIPLA', 'Cipla Ltd', 'NSE', 'Healthcare', 1),
('DIVISLAB', 'Divis Laboratories Ltd', 'NSE', 'Healthcare', 1),
('BPCL', 'Bharat Petroleum Corp Ltd', 'NSE', 'Oil Gas & Consumable Fuels', 1),
('EICHERMOT', 'Eicher Motors Ltd', 'NSE', 'Automobile', 1),
('BRITANNIA', 'Britannia Industries Ltd', 'NSE', 'FMCG', 1),
('APOLLOHOSP', 'Apollo Hospitals Enterprise', 'NSE', 'Healthcare', 1),
('INDUSINDBK', 'IndusInd Bank Ltd', 'NSE', 'Financial Services', 1),
('HEROMOTOCO', 'Hero MotoCorp Ltd', 'NSE', 'Automobile', 1),
('HINDALCO', 'Hindalco Industries Ltd', 'NSE', 'Metals & Mining', 1),
('TATACONSUM', 'Tata Consumer Products Ltd', 'NSE', 'FMCG', 1),
('SBILIFE', 'SBI Life Insurance Co', 'NSE', 'Financial Services', 1),
('HDFCLIFE', 'HDFC Life Insurance Co', 'NSE', 'Financial Services', 1),
('BAJAJ-AUTO', 'Bajaj Auto Ltd', 'NSE', 'Automobile', 1),
('ADANIPORTS', 'Adani Ports & SEZ Ltd', 'NSE', 'Services', 1),
('UPL', 'UPL Ltd', 'NSE', 'Chemicals', 1),
('SHRIRAMFIN', 'Shriram Finance Ltd', 'NSE', 'Financial Services', 1)
ON DUPLICATE KEY UPDATE company_name = VALUES(company_name), exchange = VALUES(exchange), sector = VALUES(sector);

INSERT INTO stocks_master (symbol, company_name, exchange, sector, is_active) VALUES
('AMBUJACEM', 'Ambuja Cements Ltd', 'NSE', 'Construction Materials', 1),
('BANKBARODA', 'Bank of Baroda', 'NSE', 'Financial Services', 1),
('BERGEPAINT', 'Berger Paints India Ltd', 'NSE', 'Consumer Durables', 1),
('BIOCON', 'Biocon Ltd', 'NSE', 'Healthcare', 1),
('CHOLAFIN', 'Cholamandalam Investment', 'NSE', 'Financial Services', 1),
('COLPAL', 'Colgate Palmolive India', 'NSE', 'FMCG', 1),
('DLF', 'DLF Ltd', 'NSE', 'Realty', 1),
('DABUR', 'Dabur India Ltd', 'NSE', 'FMCG', 1),
('GAIL', 'GAIL India Ltd', 'NSE', 'Oil Gas & Consumable Fuels', 1),
('GODREJCP', 'Godrej Consumer Products', 'NSE', 'FMCG', 1),
('HAVELLS', 'Havells India Ltd', 'NSE', 'Consumer Durables', 1),
('ICICIPRULI', 'ICICI Prudential Life', 'NSE', 'Financial Services', 1),
('IOC', 'Indian Oil Corp Ltd', 'NSE', 'Oil Gas & Consumable Fuels', 1),
('IRCTC', 'Indian Railway Catering & Tourism', 'NSE', 'Services', 1),
('JINDALSTEL', 'Jindal Steel & Power', 'NSE', 'Metals & Mining', 1),
('LUPIN', 'Lupin Ltd', 'NSE', 'Healthcare', 1),
('MARICO', 'Marico Ltd', 'NSE', 'FMCG', 1),
('MUTHOOTFIN', 'Muthoot Finance Ltd', 'NSE', 'Financial Services', 1),
('NAUKRI', 'Info Edge India Ltd', 'NSE', 'Information Technology', 1),
('PEL', 'Piramal Enterprises Ltd', 'NSE', 'Financial Services', 1),
('PIDILITIND', 'Pidilite Industries Ltd', 'NSE', 'Chemicals', 1),
('PNB', 'Punjab National Bank', 'NSE', 'Financial Services', 1),
('SAIL', 'Steel Authority of India', 'NSE', 'Metals & Mining', 1),
('SHREECEM', 'Shree Cement Ltd', 'NSE', 'Construction Materials', 1),
('SIEMENS', 'Siemens Ltd', 'NSE', 'Capital Goods', 1),
('SRF', 'SRF Ltd', 'NSE', 'Chemicals', 1),
('TORNTPHARM', 'Torrent Pharmaceuticals', 'NSE', 'Healthcare', 1),
('TRENT', 'Trent Ltd', 'NSE', 'Consumer Durables', 1),
('VEDL', 'Vedanta Ltd', 'NSE', 'Metals & Mining', 1),
('ZOMATO', 'Zomato Ltd', 'NSE', 'Consumer Services', 1),
('ADANIGREEN', 'Adani Green Energy Ltd', 'NSE', 'Power', 1),
('ADANIPOWER', 'Adani Power Ltd', 'NSE', 'Power', 1),
('ATGL', 'Adani Total Gas Ltd', 'NSE', 'Oil Gas & Consumable Fuels', 1),
('AWL', 'Adani Wilmar Ltd', 'NSE', 'FMCG', 1),
('CANBK', 'Canara Bank', 'NSE', 'Financial Services', 1),
('FEDERALBNK', 'Federal Bank Ltd', 'NSE', 'Financial Services', 1),
('IDFCFIRSTB', 'IDFC First Bank Ltd', 'NSE', 'Financial Services', 1),
('INDHOTEL', 'Indian Hotels Company', 'NSE', 'Consumer Services', 1),
('LICI', 'Life Insurance Corp of India', 'NSE', 'Financial Services', 1),
('LTIM', 'LTIMindtree Ltd', 'NSE', 'Information Technology', 1),
('MAXHEALTH', 'Max Healthcare Institute', 'NSE', 'Healthcare', 1),
('NHPC', 'NHPC Ltd', 'NSE', 'Power', 1),
('PAYTM', 'One97 Communications Ltd', 'NSE', 'Financial Services', 1),
('PERSISTENT', 'Persistent Systems Ltd', 'NSE', 'Information Technology', 1),
('POLYCAB', 'Polycab India Ltd', 'NSE', 'Capital Goods', 1),
('RECLTD', 'REC Ltd', 'NSE', 'Financial Services', 1),
('TATAELXSI', 'Tata Elxsi Ltd', 'NSE', 'Information Technology', 1),
('TATAPOWER', 'Tata Power Company Ltd', 'NSE', 'Power', 1),
('VOLTAS', 'Voltas Ltd', 'NSE', 'Consumer Durables', 1),
('ZYDUSLIFE', 'Zydus Lifesciences Ltd', 'NSE', 'Healthcare', 1)
ON DUPLICATE KEY UPDATE company_name = VALUES(company_name), exchange = VALUES(exchange), sector = VALUES(sector);

INSERT INTO stocks_master (symbol, company_name, exchange, sector, is_active) VALUES
('ICICIGI', 'ICICI Lombard General Insurance', 'NSE', 'Financial Services', 1),
('NYKAA', 'FSN E-Commerce Ventures', 'NSE', 'Consumer Services', 1),
('DELHIVERY', 'Delhivery Ltd', 'NSE', 'Services', 1),
('POLICYBZR', 'PB Fintech Ltd', 'NSE', 'Financial Services', 1),
('STARHEALTH', 'Star Health Insurance', 'NSE', 'Financial Services', 1),
('PIIND', 'PI Industries Ltd', 'NSE', 'Chemicals', 1),
('MCDOWELL-N', 'United Spirits Ltd', 'NSE', 'FMCG', 1),
('PAGEIND', 'Page Industries Ltd', 'NSE', 'Textiles', 1),
('ASTRAL', 'Astral Ltd', 'NSE', 'Capital Goods', 1),
('OFSS', 'Oracle Financial Services', 'NSE', 'Information Technology', 1),
('AUROPHARMA', 'Aurobindo Pharma Ltd', 'NSE', 'Healthcare', 1),
('CUMMINSIND', 'Cummins India Ltd', 'NSE', 'Capital Goods', 1),
('MPHASIS', 'MphasiS Ltd', 'NSE', 'Information Technology', 1),
('COFORGE', 'Coforge Ltd', 'NSE', 'Information Technology', 1),
('ABCAPITAL', 'Aditya Birla Capital Ltd', 'NSE', 'Financial Services', 1),
('GODREJPROP', 'Godrej Properties Ltd', 'NSE', 'Realty', 1),
('OBEROIRLTY', 'Oberoi Realty Ltd', 'NSE', 'Realty', 1),
('PHOENIXLTD', 'Phoenix Mills Ltd', 'NSE', 'Realty', 1),
('PRESTIGE', 'Prestige Estates Projects', 'NSE', 'Realty', 1),
('LODHA', 'Macrotech Developers Ltd', 'NSE', 'Realty', 1),
('SOBHA', 'Sobha Ltd', 'NSE', 'Realty', 1),
('BRIGADE', 'Brigade Enterprises Ltd', 'NSE', 'Realty', 1),
('TORNTPOWER', 'Torrent Power Ltd', 'NSE', 'Power', 1),
('CESC', 'CESC Ltd', 'NSE', 'Power', 1),
('JSWENERGY', 'JSW Energy Ltd', 'NSE', 'Power', 1),
('SJVN', 'SJVN Ltd', 'NSE', 'Power', 1),
('IREDA', 'Indian Renewable Energy Dev Agency', 'NSE', 'Financial Services', 1),
('PFC', 'Power Finance Corp Ltd', 'NSE', 'Financial Services', 1),
('HUDCO', 'Housing & Urban Development Corp', 'NSE', 'Financial Services', 1),
('IRFC', 'Indian Railway Finance Corp', 'NSE', 'Financial Services', 1),
('CANFINHOME', 'Can Fin Homes Ltd', 'NSE', 'Financial Services', 1),
('LICHSGFIN', 'LIC Housing Finance Ltd', 'NSE', 'Financial Services', 1),
('MANAPPURAM', 'Manappuram Finance Ltd', 'NSE', 'Financial Services', 1),
('POONAWALLA', 'Poonawalla Fincorp Ltd', 'NSE', 'Financial Services', 1),
('AUBANK', 'AU Small Finance Bank', 'NSE', 'Financial Services', 1),
('BANDHANBNK', 'Bandhan Bank Ltd', 'NSE', 'Financial Services', 1),
('IDBI', 'IDBI Bank Ltd', 'NSE', 'Financial Services', 1),
('UNIONBANK', 'Union Bank of India', 'NSE', 'Financial Services', 1),
('INDIANB', 'Indian Bank', 'NSE', 'Financial Services', 1),
('IOB', 'Indian Overseas Bank', 'NSE', 'Financial Services', 1),
('CENTRALBK', 'Central Bank of India', 'NSE', 'Financial Services', 1),
('UCOBANK', 'UCO Bank', 'NSE', 'Financial Services', 1),
('YESBANK', 'Yes Bank Ltd', 'NSE', 'Financial Services', 1),
('RBLBANK', 'RBL Bank Ltd', 'NSE', 'Financial Services', 1),
('KARURVYSYA', 'Karur Vysya Bank Ltd', 'NSE', 'Financial Services', 1),
('SOUTHBANK', 'South Indian Bank', 'NSE', 'Financial Services', 1),
('TMB', 'Tamilnad Mercantile Bank', 'NSE', 'Financial Services', 1),
('CUB', 'City Union Bank Ltd', 'NSE', 'Financial Services', 1),
('MAHABANK', 'Bank of Maharashtra', 'NSE', 'Financial Services', 1),
('LTTS', 'L&T Technology Services', 'NSE', 'Information Technology', 1)
ON DUPLICATE KEY UPDATE company_name = VALUES(company_name), exchange = VALUES(exchange), sector = VALUES(sector);

INSERT INTO stocks_master (symbol, company_name, exchange, sector, is_active) VALUES
('KPITTECH', 'KPIT Technologies Ltd', 'NSE', 'Information Technology', 1),
('CYIENT', 'Cyient Ltd', 'NSE', 'Information Technology', 1),
('ZENSAR', 'Zensar Technologies Ltd', 'NSE', 'Information Technology', 1),
('BIRLASOFT', 'Birlasoft Ltd', 'NSE', 'Information Technology', 1),
('SONATSOFTW', 'Sonata Software Ltd', 'NSE', 'Information Technology', 1),
('MASTEK', 'Mastek Ltd', 'NSE', 'Information Technology', 1),
('HAPPSTMNDS', 'Happiest Minds Technologies', 'NSE', 'Information Technology', 1),
('ROUTE', 'Route Mobile Ltd', 'NSE', 'Information Technology', 1),
('TANLA', 'Tanla Platforms Ltd', 'NSE', 'Information Technology', 1),
('ABBOTINDIA', 'Abbott India Ltd', 'NSE', 'Healthcare', 1),
('SANOFI', 'Sanofi India Ltd', 'NSE', 'Healthcare', 1),
('PFIZER', 'Pfizer Ltd', 'NSE', 'Healthcare', 1),
('GLAXO', 'GlaxoSmithKline Pharma', 'NSE', 'Healthcare', 1),
('IPCALAB', 'IPCA Laboratories Ltd', 'NSE', 'Healthcare', 1),
('ALKEM', 'Alkem Laboratories Ltd', 'NSE', 'Healthcare', 1),
('LAURUSLABS', 'Laurus Labs Ltd', 'NSE', 'Healthcare', 1),
('GLENMARK', 'Glenmark Pharmaceuticals', 'NSE', 'Healthcare', 1),
('NATCOPHARMA', 'Natco Pharma Ltd', 'NSE', 'Healthcare', 1),
('METROPOLIS', 'Metropolis Healthcare', 'NSE', 'Healthcare', 1),
('LALPATHLAB', 'Dr Lal PathLabs Ltd', 'NSE', 'Healthcare', 1),
('FORTIS', 'Fortis Healthcare Ltd', 'NSE', 'Healthcare', 1),
('MEDANTA', 'Global Health Ltd', 'NSE', 'Healthcare', 1),
('YATHARTH', 'Yatharth Hospital', 'NSE', 'Healthcare', 1),
('GRANULES', 'Granules India Ltd', 'NSE', 'Healthcare', 1),
('AJANTPHARM', 'Ajanta Pharma Ltd', 'NSE', 'Healthcare', 1),
('JBCHEPHARM', 'JB Chemicals & Pharma', 'NSE', 'Healthcare', 1),
('ASHOKLEY', 'Ashok Leyland Ltd', 'NSE', 'Automobile', 1),
('TVSMOTOR', 'TVS Motor Company Ltd', 'NSE', 'Automobile', 1),
('MOTHERSON', 'Samvardhana Motherson', 'NSE', 'Automobile', 1),
('BOSCHLTD', 'Bosch Ltd', 'NSE', 'Automobile', 1),
('MRF', 'MRF Ltd', 'NSE', 'Automobile', 1),
('BALKRISIND', 'Balkrishna Industries', 'NSE', 'Automobile', 1),
('APOLLOTYRE', 'Apollo Tyres Ltd', 'NSE', 'Automobile', 1),
('EXIDEIND', 'Exide Industries Ltd', 'NSE', 'Automobile', 1),
('AMARAJABAT', 'Amara Raja Energy', 'NSE', 'Automobile', 1),
('SONACOMS', 'Sona BLW Precision', 'NSE', 'Automobile', 1),
('TIINDIA', 'Tube Investments of India', 'NSE', 'Automobile', 1),
('SCHAEFFLER', 'Schaeffler India Ltd', 'NSE', 'Automobile', 1),
('SKFINDIA', 'SKF India Ltd', 'NSE', 'Automobile', 1),
('SUNDRMFAST', 'Sundram Fasteners Ltd', 'NSE', 'Automobile', 1),
('BHARATFORG', 'Bharat Forge Ltd', 'NSE', 'Capital Goods', 1),
('ABB', 'ABB India Ltd', 'NSE', 'Capital Goods', 1),
('BHEL', 'Bharat Heavy Electricals', 'NSE', 'Capital Goods', 1),
('HAL', 'Hindustan Aeronautics', 'NSE', 'Capital Goods', 1),
('BEL', 'Bharat Electronics Ltd', 'NSE', 'Capital Goods', 1),
('THERMAX', 'Thermax Ltd', 'NSE', 'Capital Goods', 1),
('KAYNES', 'Kaynes Technology India', 'NSE', 'Capital Goods', 1),
('COCHINSHIP', 'Cochin Shipyard Ltd', 'NSE', 'Capital Goods', 1),
('MAZAGONDOCK', 'Mazagon Dock Shipbuilders', 'NSE', 'Capital Goods', 1),
('GRSE', 'Garden Reach Shipbuilders', 'NSE', 'Capital Goods', 1)
ON DUPLICATE KEY UPDATE company_name = VALUES(company_name), exchange = VALUES(exchange), sector = VALUES(sector);

INSERT INTO stocks_master (symbol, company_name, exchange, sector, is_active) VALUES
('BDL', 'Bharat Dynamics Ltd', 'NSE', 'Capital Goods', 1),
('SOLARINDS', 'Solar Industries India', 'NSE', 'Capital Goods', 1),
('HONAUT', 'Honeywell Automation India', 'NSE', 'Capital Goods', 1),
('AIAENG', 'AIA Engineering Ltd', 'NSE', 'Capital Goods', 1),
('CGPOWER', 'CG Power and Industrial', 'NSE', 'Capital Goods', 1),
('ELGIEQUIP', 'Elgi Equipments Ltd', 'NSE', 'Capital Goods', 1),
('GRINFRA', 'G R Infraprojects Ltd', 'NSE', 'Capital Goods', 1),
('KEC', 'KEC International Ltd', 'NSE', 'Capital Goods', 1),
('KALPATPOWR', 'Kalpataru Projects Intl', 'NSE', 'Capital Goods', 1),
('GODREJIND', 'Godrej Industries Ltd', 'NSE', 'FMCG', 1),
('EMAMILTD', 'Emami Ltd', 'NSE', 'FMCG', 1),
('VBL', 'Varun Beverages Ltd', 'NSE', 'FMCG', 1),
('RADICO', 'Radico Khaitan Ltd', 'NSE', 'FMCG', 1),
('PGHH', 'Procter & Gamble Hygiene', 'NSE', 'FMCG', 1),
('GILLETTE', 'Gillette India Ltd', 'NSE', 'FMCG', 1),
('JUBLFOOD', 'Jubilant Foodworks Ltd', 'NSE', 'Consumer Services', 1),
('DEVYANI', 'Devyani International', 'NSE', 'Consumer Services', 1),
('SAPPHIRE', 'Sapphire Foods India', 'NSE', 'Consumer Services', 1),
('BIKAJI', 'Bikaji Foods International', 'NSE', 'FMCG', 1),
('PATANJALI', 'Patanjali Foods Ltd', 'NSE', 'FMCG', 1),
('ATUL', 'Atul Ltd', 'NSE', 'Chemicals', 1),
('DEEPAKFERT', 'Deepak Fertilisers', 'NSE', 'Chemicals', 1),
('DEEPAKNTR', 'Deepak Nitrite Ltd', 'NSE', 'Chemicals', 1),
('CLEAN', 'Clean Science & Technology', 'NSE', 'Chemicals', 1),
('NMDC', 'NMDC Ltd', 'NSE', 'Metals & Mining', 1),
('NATIONALUM', 'National Aluminium Co', 'NSE', 'Metals & Mining', 1),
('MOIL', 'MOIL Ltd', 'NSE', 'Metals & Mining', 1),
('RATNAMANI', 'Ratnamani Metals & Tubes', 'NSE', 'Metals & Mining', 1),
('APLAPOLLO', 'APL Apollo Tubes Ltd', 'NSE', 'Metals & Mining', 1),
('JSWINFRA', 'JSW Infrastructure Ltd', 'NSE', 'Services', 1),
('WELCORP', 'Welspun Corp Ltd', 'NSE', 'Metals & Mining', 1),
('HINDPETRO', 'Hindustan Petroleum Corp', 'NSE', 'Oil Gas & Consumable Fuels', 1),
('PETRONET', 'Petronet LNG Ltd', 'NSE', 'Oil Gas & Consumable Fuels', 1),
('MGL', 'Mahanagar Gas Ltd', 'NSE', 'Oil Gas & Consumable Fuels', 1),
('IGL', 'Indraprastha Gas Ltd', 'NSE', 'Oil Gas & Consumable Fuels', 1),
('GUJGASLTD', 'Gujarat Gas Ltd', 'NSE', 'Oil Gas & Consumable Fuels', 1),
('OIL', 'Oil India Ltd', 'NSE', 'Oil Gas & Consumable Fuels', 1),
('MRPL', 'Mangalore Refinery', 'NSE', 'Oil Gas & Consumable Fuels', 1),
('CHENNPETRO', 'Chennai Petroleum Corp', 'NSE', 'Oil Gas & Consumable Fuels', 1),
('ACC', 'ACC Ltd', 'NSE', 'Construction Materials', 1),
('RAMCOCEM', 'Ramco Cements Ltd', 'NSE', 'Construction Materials', 1),
('JKCEMENT', 'JK Cement Ltd', 'NSE', 'Construction Materials', 1),
('DALBHARAT', 'Dalmia Bharat Ltd', 'NSE', 'Construction Materials', 1),
('JKLAKSHMI', 'JK Lakshmi Cement Ltd', 'NSE', 'Construction Materials', 1),
('BIRLACEM', 'Nuvoco Vistas Corp Ltd', 'NSE', 'Construction Materials', 1),
('STARCEMENT', 'Star Cement Ltd', 'NSE', 'Construction Materials', 1),
('IDEA', 'Vodafone Idea Ltd', 'NSE', 'Telecommunication', 1),
('TATACOMM', 'Tata Communications', 'NSE', 'Telecommunication', 1),
('ZEEL', 'Zee Entertainment', 'NSE', 'Media', 1),
('SUNTV', 'Sun TV Network Ltd', 'NSE', 'Media', 1)
ON DUPLICATE KEY UPDATE company_name = VALUES(company_name), exchange = VALUES(exchange), sector = VALUES(sector);

INSERT INTO stocks_master (symbol, company_name, exchange, sector, is_active) VALUES
('PVR', 'PVR INOX Ltd', 'NSE', 'Media', 1),
('IRCON', 'Ircon International Ltd', 'NSE', 'Construction', 1),
('NBCC', 'NBCC India Ltd', 'NSE', 'Construction', 1),
('NCC', 'NCC Ltd', 'NSE', 'Construction', 1),
('RVNL', 'Rail Vikas Nigam Ltd', 'NSE', 'Construction', 1),
('RAILTEL', 'RailTel Corporation', 'NSE', 'Information Technology', 1),
('CONCOR', 'Container Corp of India', 'NSE', 'Services', 1),
('BATAINDIA', 'Bata India Ltd', 'NSE', 'Consumer Durables', 1),
('WHIRLPOOL', 'Whirlpool of India Ltd', 'NSE', 'Consumer Durables', 1),
('CROMPTON', 'Crompton Greaves Consumer', 'NSE', 'Consumer Durables', 1),
('BLUESTARCO', 'Blue Star Ltd', 'NSE', 'Consumer Durables', 1),
('DIXON', 'Dixon Technologies Ltd', 'NSE', 'Consumer Durables', 1),
('KAJARIACER', 'Kajaria Ceramics Ltd', 'NSE', 'Consumer Durables', 1),
('CENTURYTEX', 'Century Textiles', 'NSE', 'Consumer Durables', 1),
('RELAXO', 'Relaxo Footwears Ltd', 'NSE', 'Consumer Durables', 1),
('METROBRAND', 'Metro Brands Ltd', 'NSE', 'Consumer Durables', 1),
('CAMPUS', 'Campus Activewear Ltd', 'NSE', 'Consumer Durables', 1),
('GICRE', 'General Insurance Corp', 'NSE', 'Financial Services', 1),
('NIACL', 'New India Assurance Co', 'NSE', 'Financial Services', 1),
('DMART', 'Avenue Supermarts Ltd', 'NSE', 'Consumer Services', 1),
('GNFC', 'Gujarat Narmada Valley', 'NSE', 'Chemicals', 1),
('GSFC', 'Gujarat State Fertilizers', 'NSE', 'Chemicals', 1),
('CHAMBLFERT', 'Chambal Fertilisers', 'NSE', 'Chemicals', 1),
('COROMANDEL', 'Coromandel International', 'NSE', 'Chemicals', 1),
('SUMICHEM', 'Sumitomo Chemical India', 'NSE', 'Chemicals', 1),
('AAVAS', 'Aavas Financiers Ltd', 'NSE', 'Financial Services', 1),
('AARTIIND', 'Aarti Industries Ltd', 'NSE', 'Chemicals', 1),
('ABFRL', 'Aditya Birla Fashion', 'NSE', 'Consumer Durables', 1),
('ABSLAMC', 'Aditya Birla Sun Life AMC', 'NSE', 'Financial Services', 1),
('AEGISCHEM', 'Aegis Logistics Ltd', 'NSE', 'Oil Gas & Consumable Fuels', 1),
('AFFLE', 'Affle India Ltd', 'NSE', 'Information Technology', 1),
('ALKYLAMINE', 'Alkyl Amines Chemicals', 'NSE', 'Chemicals', 1),
('ALOKINDS', 'Alok Industries Ltd', 'NSE', 'Textiles', 1),
('ANGELONE', 'Angel One Ltd', 'NSE', 'Financial Services', 1),
('APTUS', 'Aptus Value Housing Finance', 'NSE', 'Financial Services', 1),
('ARVIND', 'Arvind Ltd', 'NSE', 'Textiles', 1),
('ASHOKA', 'Ashoka Buildcon Ltd', 'NSE', 'Construction', 1),
('BSOFT', 'BIRLASOFT Ltd', 'NSE', 'Information Technology', 1),
('BSE', 'BSE Ltd', 'NSE', 'Financial Services', 1),
('CARBORUNIV', 'Carborundum Universal', 'NSE', 'Capital Goods', 1),
('CDSL', 'Central Depository Services', 'NSE', 'Financial Services', 1),
('CENTURYPLY', 'Century Plyboards India', 'NSE', 'Consumer Durables', 1),
('CHALET', 'Chalet Hotels Ltd', 'NSE', 'Consumer Services', 1),
('DATAPATTNS', 'Data Patterns India', 'NSE', 'Capital Goods', 1),
('DCMSHRIRAM', 'DCM Shriram Ltd', 'NSE', 'Chemicals', 1),
('ECLERX', 'eClerx Services Ltd', 'NSE', 'Information Technology', 1),
('EIDPARRY', 'EID Parry India Ltd', 'NSE', 'FMCG', 1),
('ESCORTS', 'Escorts Kubota Ltd', 'NSE', 'Automobile', 1),
('FINEORG', 'Fine Organic Industries', 'NSE', 'Chemicals', 1),
('FLUOROCHEM', 'Gujarat Fluorochemicals', 'NSE', 'Chemicals', 1)
ON DUPLICATE KEY UPDATE company_name = VALUES(company_name), exchange = VALUES(exchange), sector = VALUES(sector);

INSERT INTO stocks_master (symbol, company_name, exchange, sector, is_active) VALUES
('GLAND', 'Gland Pharma Ltd', 'NSE', 'Healthcare', 1),
('GMRAIRPORT', 'GMR Airports Infra', 'NSE', 'Services', 1),
('GODREJAGRO', 'Godrej Agrovet Ltd', 'NSE', 'FMCG', 1),
('GSPL', 'Gujarat State Petronet', 'NSE', 'Oil Gas & Consumable Fuels', 1),
('HEG', 'HEG Ltd', 'NSE', 'Capital Goods', 1),
('HFCL', 'HFCL Ltd', 'NSE', 'Telecommunication', 1),
('HINDCOPPER', 'Hindustan Copper Ltd', 'NSE', 'Metals & Mining', 1),
('HINDZINC', 'Hindustan Zinc Ltd', 'NSE', 'Metals & Mining', 1),
('IDFC', 'IDFC Ltd', 'NSE', 'Financial Services', 1),
('IEX', 'Indian Energy Exchange', 'NSE', 'Financial Services', 1),
('INDIACEM', 'India Cements Ltd', 'NSE', 'Construction Materials', 1),
('INDIGO', 'InterGlobe Aviation Ltd', 'NSE', 'Services', 1),
('INOXWIND', 'Inox Wind Ltd', 'NSE', 'Capital Goods', 1),
('INTELLECT', 'Intellect Design Arena', 'NSE', 'Information Technology', 1),
('JIOFIN', 'Jio Financial Services Ltd', 'NSE', 'Financial Services', 1),
('JKPAPER', 'JK Paper Ltd', 'NSE', 'Capital Goods', 1),
('JMFINANCIL', 'JM Financial Ltd', 'NSE', 'Financial Services', 1),
('JSL', 'Jindal Stainless Ltd', 'NSE', 'Metals & Mining', 1),
('JTEKTINDIA', 'JTEKT India Ltd', 'NSE', 'Automobile', 1),
('JYOTHYLAB', 'Jyothy Labs Ltd', 'NSE', 'FMCG', 1),
('KALYANKJIL', 'Kalyan Jewellers India', 'NSE', 'Consumer Durables', 1),
('KEI', 'KEI Industries Ltd', 'NSE', 'Capital Goods', 1),
('KIMS', 'Krishna Institute of Medical', 'NSE', 'Healthcare', 1),
('KRBL', 'KRBL Ltd', 'NSE', 'FMCG', 1),
('LAXMIMACH', 'Lakshmi Machine Works', 'NSE', 'Capital Goods', 1),
('LLOYDSME', 'Lloyds Metals & Energy', 'NSE', 'Metals & Mining', 1),
('LTFOODS', 'LT Foods Ltd', 'NSE', 'FMCG', 1),
('MCX', 'Multi Commodity Exchange', 'NSE', 'Financial Services', 1),
('MEDPLUS', 'MedPlus Health Services', 'NSE', 'Healthcare', 1),
('MOTILALOFS', 'Motilal Oswal Financial', 'NSE', 'Financial Services', 1),
('NAM-INDIA', 'Nippon Life India AMC', 'NSE', 'Financial Services', 1),
('NAVINFLUOR', 'Navin Fluorine International', 'NSE', 'Chemicals', 1),
('NETWORK18', 'Network18 Media', 'NSE', 'Media', 1),
('OLECTRA', 'Olectra Greentech Ltd', 'NSE', 'Automobile', 1),
('PNBHOUSING', 'PNB Housing Finance', 'NSE', 'Financial Services', 1),
('POWERMECH', 'Power Mech Projects', 'NSE', 'Construction', 1),
('PVRINOX', 'PVR INOX Ltd', 'NSE', 'Consumer Services', 1),
('RAJESHEXPO', 'Rajesh Exports Ltd', 'NSE', 'Consumer Durables', 1),
('RAYMOND', 'Raymond Ltd', 'NSE', 'Textiles', 1),
('REDINGTON', 'Redington Ltd', 'NSE', 'Information Technology', 1),
('SBICARD', 'SBI Cards & Payment Services', 'NSE', 'Financial Services', 1),
('SIGNATURE', 'Signatureglobal India', 'NSE', 'Realty', 1),
('SUPRAJIT', 'Suprajit Engineering', 'NSE', 'Automobile', 1),
('SUVENPHAR', 'Suven Pharmaceuticals', 'NSE', 'Healthcare', 1),
('SYNGENE', 'Syngene International', 'NSE', 'Healthcare', 1),
('TATACHEM', 'Tata Chemicals Ltd', 'NSE', 'Chemicals', 1),
('TATAINVEST', 'Tata Investment Corp', 'NSE', 'Financial Services', 1),
('TITAGARH', 'Titagarh Rail Systems', 'NSE', 'Capital Goods', 1),
('TRIVENI', 'Triveni Engineering', 'NSE', 'FMCG', 1),
('TRIDENT', 'Trident Ltd', 'NSE', 'Textiles', 1)
ON DUPLICATE KEY UPDATE company_name = VALUES(company_name), exchange = VALUES(exchange), sector = VALUES(sector);

INSERT INTO stocks_master (symbol, company_name, exchange, sector, is_active) VALUES
('TVSSCS', 'TVS Supply Chain Solutions', 'NSE', 'Services', 1),
('UTIAMC', 'UTI AMC Ltd', 'NSE', 'Financial Services', 1),
('VAIBHAVGBL', 'Vaibhav Global Ltd', 'NSE', 'Consumer Durables', 1),
('VGUARD', 'V-Guard Industries Ltd', 'NSE', 'Consumer Durables', 1),
('VINATIORGA', 'Vinati Organics Ltd', 'NSE', 'Chemicals', 1),
('VSTIND', 'VST Industries Ltd', 'NSE', 'FMCG', 1),
('NLCINDIA', 'NLC India Ltd', 'NSE', 'Power', 1),
('NMDCSTEEL', 'NMDC Steel Ltd', 'NSE', 'Metals & Mining', 1),
('BEML', 'BEML Ltd', 'NSE', 'Capital Goods', 1),
('HSCL', 'Himadri Speciality Chemical', 'NSE', 'Chemicals', 1),
('ITI', 'ITI Ltd', 'NSE', 'Telecommunication', 1),
('MAZDOCK', 'Mazagon Dock Shipbuilders', 'NSE', 'Capital Goods', 1),
('MIDHANI', 'Mishra Dhatu Nigam', 'NSE', 'Metals & Mining', 1),
('ENGINERSIN', 'Engineers India Ltd', 'NSE', 'Construction', 1),
('GMDCLTD', 'Gujarat Mineral Dev Corp', 'NSE', 'Metals & Mining', 1),
('NFL', 'National Fertilizers Ltd', 'NSE', 'Chemicals', 1),
('RCF', 'Rashtriya Chemicals', 'NSE', 'Chemicals', 1),
('RATEGAIN', 'RateGain Travel Technologies', 'NSE', 'Information Technology', 1),
('SWARAJENG', 'Swaraj Engines Ltd', 'NSE', 'Automobile', 1),
('SUZLON', 'Suzlon Energy Ltd', 'NSE', 'Capital Goods', 1),
('TATVA', 'Tatva Chintan Pharma', 'NSE', 'Chemicals', 1),
('TTML', 'Tata Teleservices Maharashtra', 'NSE', 'Telecommunication', 1),
('UJJIVANSFB', 'Ujjivan Small Finance Bank', 'NSE', 'Financial Services', 1),
('EQUITASBNK', 'Equitas Small Finance Bank', 'NSE', 'Financial Services', 1),
('FINPIPE', 'Finolex Industries Ltd', 'NSE', 'Capital Goods', 1),
('FINOLEX', 'Finolex Cables Ltd', 'NSE', 'Capital Goods', 1),
('GHCL', 'GHCL Ltd', 'NSE', 'Chemicals', 1),
('GESHIP', 'Great Eastern Shipping', 'NSE', 'Services', 1),
('JBMA', 'JBM Auto Ltd', 'NSE', 'Automobile', 1),
('JSPL', 'Jindal Steel & Power', 'NSE', 'Metals & Mining', 1),
('KANSAINER', 'Kansai Nerolac Paints', 'NSE', 'Consumer Durables', 1),
('KFINTECH', 'KFin Technologies Ltd', 'NSE', 'Financial Services', 1),
('LATENTVIEW', 'Latent View Analytics', 'NSE', 'Information Technology', 1),
('MFSL', 'Max Financial Services', 'NSE', 'Financial Services', 1),
('MMTC', 'MMTC Ltd', 'NSE', 'Services', 1),
('MOREPENLAB', 'Morepen Laboratories', 'NSE', 'Healthcare', 1),
('NAVNETEDUL', 'Navneet Education Ltd', 'NSE', 'Consumer Services', 1),
('NESCO', 'Nesco Ltd', 'NSE', 'Realty', 1),
('IIFL', 'IIFL Finance Ltd', 'NSE', 'Financial Services', 1),
('PPLPHARMA', 'Piramal Pharma Ltd', 'NSE', 'Healthcare', 1),
('PRINCEPIPE', 'Prince Pipes and Fittings', 'NSE', 'Capital Goods', 1),
('QUESS', 'Quess Corp Ltd', 'NSE', 'Services', 1),
('RITES', 'RITES Ltd', 'NSE', 'Construction', 1),
('SAKSOFT', 'Saksoft Ltd', 'NSE', 'Information Technology', 1),
('SPARC', 'Sun Pharma Advanced Research', 'NSE', 'Healthcare', 1),
('SUNDARMFIN', 'Sundaram Finance Ltd', 'NSE', 'Financial Services', 1),
('SUNTECK', 'Sunteck Realty Ltd', 'NSE', 'Realty', 1),
('SYMPHONY', 'Symphony Ltd', 'NSE', 'Consumer Durables', 1),
('TATATECH', 'Tata Technologies Ltd', 'NSE', 'Information Technology', 1),
('TIMKEN', 'Timken India Ltd', 'NSE', 'Capital Goods', 1)
ON DUPLICATE KEY UPDATE company_name = VALUES(company_name), exchange = VALUES(exchange), sector = VALUES(sector);

INSERT INTO stocks_master (symbol, company_name, exchange, sector, is_active) VALUES
('UNOMINDA', 'UNO Minda Ltd', 'NSE', 'Automobile', 1),
('WOCKPHARMA', 'Wockhardt Ltd', 'NSE', 'Healthcare', 1),
('ZFCVINDIA', 'ZF Commercial Vehicle', 'NSE', 'Automobile', 1),
('CAMS', 'Computer Age Management', 'NSE', 'Financial Services', 1),
('SYRMA', 'Syrma SGS Technology', 'NSE', 'Capital Goods', 1),
('CRAFTSMAN', 'Craftsman Automation', 'NSE', 'Capital Goods', 1),
('CIE', 'CIE Automotive India', 'NSE', 'Automobile', 1),
('GPIL', 'Godawari Power & Ispat', 'NSE', 'Metals & Mining', 1),
('ISGEC', 'Isgec Heavy Engineering', 'NSE', 'Capital Goods', 1),
('JAMNAAUTO', 'Jamna Auto Industries', 'NSE', 'Automobile', 1),
('JUSTDIAL', 'Just Dial Ltd', 'NSE', 'Consumer Services', 1),
('M&MFIN', 'Mahindra & Mahindra Financial', 'NSE', 'Financial Services', 1),
('J&KBANK', 'Jammu & Kashmir Bank', 'NSE', 'Financial Services', 1),
('ARE&M', 'Amara Raja Energy & Mobility', 'NSE', 'Automobile', 1)
ON DUPLICATE KEY UPDATE company_name = VALUES(company_name), exchange = VALUES(exchange), sector = VALUES(sector);

